// <auto-generated />
using System;
using GEL.Services.PostAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GEL.Services.PostAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211016030039_SeedPosts")]
    partial class SeedPosts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.1.21452.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GEL.Services.PostAPI.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Comments")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            CategoryId = 1,
                            Comments = 1,
                            Content = "Content 1",
                            CreatedAt = new DateTime(2021, 10, 16, 10, 0, 39, 606, DateTimeKind.Local).AddTicks(403),
                            Description = "Desc 1",
                            PublishedAt = new DateTime(2021, 10, 16, 10, 0, 39, 606, DateTimeKind.Local).AddTicks(413),
                            Slug = "Slug 1",
                            SubCategoryId = 1,
                            Thumbnail = "",
                            Title = "Post 1",
                            UpdatedAt = new DateTime(2021, 10, 16, 10, 0, 39, 606, DateTimeKind.Local).AddTicks(414),
                            Views = 1
                        },
                        new
                        {
                            PostId = 2,
                            CategoryId = 2,
                            Comments = 2,
                            Content = "Content 2",
                            CreatedAt = new DateTime(2021, 10, 16, 10, 0, 39, 606, DateTimeKind.Local).AddTicks(438),
                            Description = "Desc 2",
                            PublishedAt = new DateTime(2021, 10, 16, 10, 0, 39, 606, DateTimeKind.Local).AddTicks(438),
                            Slug = "Slug 2",
                            SubCategoryId = 2,
                            Thumbnail = "",
                            Title = "Post 2",
                            UpdatedAt = new DateTime(2021, 10, 16, 10, 0, 39, 606, DateTimeKind.Local).AddTicks(439),
                            Views = 2
                        },
                        new
                        {
                            PostId = 3,
                            CategoryId = 3,
                            Comments = 3,
                            Content = "Content 3",
                            CreatedAt = new DateTime(2021, 10, 16, 10, 0, 39, 606, DateTimeKind.Local).AddTicks(447),
                            Description = "Desc 3",
                            PublishedAt = new DateTime(2021, 10, 16, 10, 0, 39, 606, DateTimeKind.Local).AddTicks(447),
                            Slug = "Slug 3",
                            SubCategoryId = 3,
                            Thumbnail = "",
                            Title = "Post 3",
                            UpdatedAt = new DateTime(2021, 10, 16, 10, 0, 39, 606, DateTimeKind.Local).AddTicks(448),
                            Views = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
